name: Generate Dynamic SVG

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *' # Runs every hour (adjust as needed)

jobs:
  generate-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run SVG Generator Script
        run: |
          npm install
          node generateSVG.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dynamic-typing.svg
          git commit -m "Update dynamic SVG"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
