name: Generate Dynamic SVG

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  generate-svg:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Run the SVG Generator Script
      - name: Run SVG Generator Script
        run: |
          npm install
          node generateSVG.js

      # Step 4: Debug to confirm the SVG file content
      - name: Debug Generated File
        run: cat dynamic-typing.svg

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A # Adds all changes, including untracked files
          git commit -m "Update dynamic SVG" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
